{{- if eq .Values.db.create true }}
apiVersion: batch/v1
kind: Job
metadata:
  name: create-postgres-db
  labels:
    {{- include "incident-commander.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: create-postgres-db
          image: usql/postgres
          envFrom:
            - secretRef:
                name: {{ .Values.db.secretKeyRef.name | default "postgres-connection" }}
          command: ["bash"]
          args:
            - -c
            - PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -U $POSTGRES_USER -c 'create database "incident_commander"'

      restartPolicy: Never
{{- end }}
