courier:
  smtp:
    connection_uri: smtp://wrong-url
serve:
  public:
    base_url: {{ .Values.kratosURI | quote }}
    cors:
      enabled: true
  # admin:
  #   base_url: http://127.0.0.1:4434/
selfservice:
  default_browser_return_url: "{{ .Values.uiHost }}/"
  allowed_return_urls:
    - {{ .Values.uiHost | quote }}
  methods:
    password:
      enabled: true
  flows:
    error:
      ui_url: "{{ .Values.uiHost }}/error"
    settings:
      ui_url: "{{ .Values.uiHost }}/settings"
      privileged_session_max_age: 15m
    recovery:
      enabled: true
      ui_url: "{{ .Values.uiHost }}/recovery"
    verification:
      enabled: true
      ui_url: "{{ .Values.uiHost }}/verification"
      after:
        default_browser_return_url: "{{ .Values.uiHost }}/"
    logout:
      after:
        default_browser_return_url: "{{ .Values.uiHost }}/login"
    login:
      ui_url: "{{ .Values.uiHost }}/login"
      lifespan: 10m
    registration:
      lifespan: 10m
      ui_url: "{{ .Values.uiHost }}/registration"
      after:
        password:
          hooks:
            -
              hook: session
log:
  level: info
  leak_sensitive_values: false
identity:
  schemas:
    - id: default
      url: base64://{{ (.Files.Get "files/kratos-identity-schema.json") | b64enc }}
secrets:
  default:
    - lorem ipsum dolores
    - just a random a string secret
